---
title: "Voter Turnout"
output: github_document
date: '2022-12-12'
---

```{r setup, include=FALSE}
devtools::install_github("forestry-labs/causalToolbox")
```

```{r load packages}
library(causalToolbox)
library(data.table)
library(magrittr)
library(ggplot2)
```

```{r set plot params}
# can't not...
theme_set(theme_minimal())
knitr::opts_chunk$set(dpi=300)
```


```{r}
d_individual <- fread('http://hdl.handle.net/10079/d3669799-4537-411e-b175-d9e837324c35')
d_household  <- fread('http://hdl.handle.net/10079/sxksn6q')
```

```{r subsample to get working}
d_individual <- d_individual[sample(1:.N, size=100000)]
```


```{r cleaning}
d_individual[ , voted_numeric     := (voted == 'Yes') * 1]
d_individual[ , treatment_numeric := (treatment == ' Civic Duty') * 1]
```

# Look at Civic Duty Effect 

The main result reported in the paper is the effect of civic duty. Begin by replicating this effect on the current data. 

```{r}
SUBSET <- c(' Civic Duty', ' Control')

d_individual[treatment %in% SUBSET][
  , .(mean_vote = mean(voted == 'Yes'), 
      sem       = sqrt( (var(voted == 'Yes')) / .N)), by = .(treatment)]

d_individual[treatment %in% SUBSET][ 
  , t.test(voted == 'Yes' ~ treatment)]
```

So, yes, we're seeing the same effect as was reported. 

# Causal Toolbox 

```{r train model}
model_1 <- X_RF(
  feat = d_individual[treatment %in% SUBSET, .(factor(sex), yob, hh_size, g2004_mean)],
  tr   = d_individual[treatment %in% SUBSET, treatment_numeric], 
  yobs = d_individual[treatment %in% SUBSET, voted_numeric]
)
```

```{r}
est_cate_1 <- EstimateCate(
  theObject = model_1, 
  feature_new = d_individual[treatment %in% SUBSET, .(factor(sex), yob, hh_size, g2004_mean)]
  )
```

```{r reattach to dataframe}
d_individual[treatment %in% SUBSET, estimated_cate := est_cate_1]
```

```{r}
d_individual[treatment %in% SUBSET, .(means = mean(voted_numeric)), keyby = .(treatment)][,-1*diff(means)]
d_individual[treatment %in% SUBSET, mean(estimated_cate)]
```

```{r}
d_individual[treatment %in% SUBSET, age := (2004 - yob)] %>% 
  ggplot() + 
  aes(x=age, y=estimated_cate) + 
  geom_jitter() + 
  stat_smooth()
```


