---
title: "doubleML"
author: "Jerry Gonzalez"
date: "2024-09-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r doubleML}
library(data.table) 
library(MASS)
library(stargazer)

x_matrix <- MASS::mvrnorm(
  n = 10000, 
  mu = c(1,2,3), 
  Sigma = matrix(
    data = c(
      10, -5, 1,     # diagonal are variance; 
      -5,  5, 2,     # off diagnoals are covariances
       1,  2, 3), 
    nrow = 3, ncol = 3
  )
)

d <- data.table(
  id  = 1:10000
)

d[ , ':='(
  x1      = x_matrix[,1], 
  x2      = x_matrix[,2], 
  epsilon = x_matrix[,3]
  )]

d[ , treat_continuous := 0 + rnorm(n=.N, mean=3, sd=1) + (1*x1) + (2*x2) + (15*epsilon)]
d[ , treat_binary     := treat_continuous > quantile(treat_continuous, 0.9)]

#d[ , Y := 0 * 1*x1 + 2*x2 + 3*treat_binary + 15*epsilon + rnorm(n=.N, mean=0, sd=1)]
#d[ , Y := 0 * 1*x1 + 2*x2 + 3*treat_binary + rnorm(n=.N, mean=0, sd=1)]
d[ , Y := 0 * 1*x1 + 2*I(x2^2) + 3*treat_binary + rnorm(n=.N, mean=0, sd=1)]
d[ , t.test(Y ~ treat_binary)]

model_1 <- d[ , lm(Y ~ treat_binary)]
model_2 <- d[ , lm(Y ~ x1 + treat_binary)]
model_3 <- d[ , lm(Y ~ x2 + treat_binary)]
model_4 <- d[ , lm(Y ~ x1 + x2 + treat_binary)]
model_5 <- d[ , lm(Y ~ x1 + x2  + epsilon + treat_binary)]
model_6 <- d[ , lm(Y ~ x1 + I(x2^2)  + epsilon + treat_binary)]

stargazer(
  model_1, model_2, model_3, model_4, model_5, model_6,
  type = 'text', 
  omit.stat = c("ser", "F")
)

fwrite(
  x    = d[ , .(Y, x1, x2, treat_binary)], 
  file = "./Downloads/causal_challenge_limited_data.csv"
  )
fwrite(
  x    = d[ , .(Y, x1, x2, treat_binary, epsilon)], 
  file = "./Downloads/causal_challenge_full_data.csv"
)
```


